/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { Configuration, OpenAIApi } from "openai";
import { useState } from "react";
import AirplaneIcon from "./components/AirplaneIcon";
import LoaderIcon from "./components/LoaderIcon";
export default function Home() {
    const [prompt, setPrompt] = useState("");
    const [imageUrl, setImageUrl] = useState("");
    const [loading, setLoading] = useState(false);
    const configuration = new Configuration({
        apiKey: process.env.NEXT_PUBLIC_API_KEY,
    });
    const openai = new OpenAIApi(configuration);

    const handleSubmit = async (e) => {
        e.preventDefault();
        setLoading(true);
        try {
            const response = await openai.createImage({
                prompt: prompt,
                n: 1,
                size: "512x512",
            });
            setImageUrl(response?.data?.data[0]?.url);
        } catch (error) {
            console.log(error);
        }
        setLoading(false);
    };

    return (
        <>
            <Head>
                <title>Image Make With Chat Gpt</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-gradient-to-b min-h-screen flex items-center justify-center from-gray-700 to-gray-900">
                <div className="w-10/12 lg:w-7/12 mx-auto">
                    <form className="" onSubmit={handleSubmit}>
                        <div className="flex relative">
                            <input
                                className="w-full p-4 lg:p-5 focus:outline-none rounded bg-gray-600 text-base lg:text-lg text-white"
                                value={prompt}
                                onChange={(e) => setPrompt(e.target.value)}
                                type="text"
                                placeholder="What Type of image you want to generate"
                            />
                            {!loading ? <AirplaneIcon /> : <LoaderIcon />}
                        </div>
                    </form>
                    {imageUrl && (
                        <div className="w-full mx-auto rounded-xl pt-10">
                            <img
                                src={imageUrl}
                                alt="open ai generated"
                                className="mx-auto rounded-xl"
                            />
                        </div>
                    )}
                </div>
            </main>
        </>
    );
}
